@baseUrl = http://localhost:8080
@participantId = c40d31d5-9dea-46f4-915c-7429e7f6dff7
@tripId = 42bf829c-3faa-424c-9ff4-d9b061561002
@linkId = 72ec7b6d-26e9-404c-8b7f-fb613187e07e

### --------------------- // ---------------------

### Trips

#### Fetch a Specific Trip
GET {{baseUrl}}/trips/{{tripId}}
###

#### Create a New Trip
POST {{baseUrl}}/trips
Content-Type: application/json

{
  "destination": "Japan",
  "starts_at": "2024-07-10T19:53:09.884Z",
  "ends_at": "2024-07-28T19:53:09.884Z",
  "emails_to_invite": [
    "user@example.com",
    "user2@example.com"
  ],
  "owner_name": "Higor",
  "owner_email": "contact@higorjardini.dev"
}
###

#### Update Trip Details
PUT {{baseUrl}}/trips/{{tripId}}
Content-Type: application/json

{
  "destination": "Korea",
  "starts_at": "2024-09-29T19:53:09.884Z",
  "ends_at": "2024-10-11T19:53:09.884Z"
}
###

#### Confirm a Trip
GET {{baseUrl}}/trips/{{tripId}}/confirm
###

### --------------------- // ---------------------

### Participants

#### Get Participants of a Trip
GET {{baseUrl}}/trips/{{tripId}}/participants
###

#### Confirm a Participant
PATCH {{baseUrl}}/participants/{{participantId}}/confirm
###

#### Invite a New Participant to a Trip
POST {{baseUrl}}/trips/{{tripId}}/invites
Content-Type: application/json

{
  "email": "contact2@higorjardini.dev"
}
###

### --------------------- // ---------------------

### Activities

#### Create a New Activity for a Trip
POST {{baseUrl}}/trips/{{tripId}}/activities
Content-Type: application/json

{
  "occurs_at": "2024-10-13T19:53:09.884Z",
  "title": "Shibuya"
}
###

#### Get Activities of a Trip
GET {{baseUrl}}/trips/{{tripId}}/activities
###

### --------------------- // ---------------------

### Links

#### Add a Link to a Trip
POST {{baseUrl}}/trips/{{tripId}}/links
Content-Type: application/json

{
  "title": "Airbnb",
  "url": "https://www.airbnb.com.br/"
}
###

#### Get Links of a Trip
GET {{baseUrl}}/trips/{{tripId}}/links
###