###
PATCH  http://localhost:8080/participants/c40d31d5-9dea-46f4-915c-7429e7f6dff7/confirm

###
POST http://localhost:8080/trips
Content-Type: application/json

{
  "destination": "Japan",
  "starts_at": "2024-07-10T19:53:09.884Z",
  "ends_at": "2024-07-28T19:53:09.884Z",
  "emails_to_invite": [
    "user@example.com",
    "user2@example.com"
  ],
  "owner_name": "Higor",
  "owner_email": "contact@higorjardini.dev"
}